# .github/workflows/unity-android.yml
name: Unity Build (Android)

on:
  push:
    branches: [ main, master ]
  pull_request: {}

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: unity/first/Library
          key: Library-${{ runner.os }}-Android-${{ hashFiles('unity/first/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-Android-
            Library-${{ runner.os }}-

      - name: Build (Android)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # или для Pro:
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: unity/first
          targetPlatform: Android
          buildPath: unity/first/build/Android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android
          path: unity/first/build/Android
