# .github/workflows/build-android-apk.yml
name: Build Android APK (Unity)

on:
  pull_request_target:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-android:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          lfs: true
          fetch-depth: 0

      # освобождаем место ДО docker pull unityci/editor
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/cache@v4
        with:
          path: unity/first/Library
          key: Library-${{ runner.os }}-Android-${{ hashFiles('unity/first/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-Android-
            Library-${{ runner.os }}-

      - name: Build (Android)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: unity/first
          targetPlatform: Android
          buildsPath: unity/first/build   # <-- вместо buildPath
          buildName: Android              # будет unity/first/build/Android/Android.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Android
          path: unity/first/build/Android
